### ISSUE TITLE
Expose sync ports 22000 and 21027

### ISSUE THREAD

**Issue by Zillode** [linuxserver/docker-syncthing#1]
See http://docs.syncthing.net/users/firewall.html#local-firewall
and https://github.com/linuxserver/docker-syncthing/blob/dd30a71c90cfb16d57642d20a9103ce3925901d7/Dockerfile#L24

**Comment by IronicBadger** [comment]
By using `--net=host` we negate the need to specify multiple ports. The `EXPOSE` will be removed.

**Comment by lonix** [comment]
I Have some time to show this container some love later today. This issue will be looked at then.
