### ISSUE TITLE
https://DOMAIN:8384/rest/system/upgrade Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Mrono** [linuxserver/docker-syncthing#12]
When loading the page I get the above error, I also get the following in error logs

WARNING: Decoding posted config: read tcp 172.17.0.9:8384->IP:58684: i/o timeout

Latest version of the docker image

I also get a lot of INFO: Connected to myself (DDYUFAJ-SL7A5ZF-M23J3SP-NL3TDZV-RC5UXO5-PVITIMD-HPX73F4-CWPCSQV) - should not happen

docker create   --name=syncthing   -v /storage/folder/config:/config   -v /storage/folder/data:/data   -e PGID=1001 -e PUID=1001    -p 8384:8384 -p 22000:22000 -p 21027:21027/udp   linuxserver/syncthing

**Comment by Mrono** [comment]
A minute after I load the page I get a red error message about en error has occured and I need to reload the page

**Comment by dodekeract** [comment]
Does this happen for an empty container? As in no config files, no data, nothing?

**Comment by Mrono** [comment]
Yes, I tried with both a new mount folder and with no mounts, same error both times right away.  I believe this is actually a browser/firewall issue.  I was able to access everything just fine via another browser, however the 500 error is still occuring
