### ISSUE TITLE
Auto generate username and password when making GUI publicly accessible

### ISSUE THREAD

**Issue by Zillode** [linuxserver/docker-syncthing#2]
When binding the GUI to 0.0.0.0 you'll definitely want to set up username and password protection.
See https://github.com/syncthing/syncthing/pull/2131 and https://github.com/linuxserver/docker-syncthing/commit/210519640dc2ad8226c034aa25b88bde07a8ddba

**Comment by IronicBadger** [comment]
I have no aversion to sorting this but shouldn't this really be up to the end user to sort out for themselves?

**Comment by Zillode** [comment]
ok, maybe it can be mentioned in the readme?

**Comment by lonix** [comment]
I Have some time to show this container some love later today. This issue will be looked at then.
