### ISSUE TITLE
Additional Binaries and Image Size

### ISSUE THREAD

**Issue by Dargmuesli** [linuxserver/docker-syncthing#21]
Why is the syncthing binary being installed here by itself, followed by the other compiled binaries in a loop? 

https://github.com/linuxserver/docker-syncthing/blob/f00a65bfc32edb62bc58a0f7bea812dc8e853ed4/Dockerfile#L38-L45

The official syncthing release is around 7.5 / 15.6 MB large whereas this image weights 49.7 MB / 162 MB (each download / extracted size). Of course 6.9 MB come from lsiobase/alpine.arm64, but still: is it necessary to pack stbench, stcli, stcompdirs, stdisco, stdiscosrv, stevents, stfileinfo, stfinddevice, stfindignored, stgenfiles, stindex, strelaypoolsrv, strelaysrv, stsigtool, stvanity, stwatchfile, testutil, uraggregate, ursrv into the package too?

**Comment by thelamer** [comment]
We cannot predict what our users will and will not use. 
Working support on this front I can tell you removing these in mass or selectively will lead to even more issues and PRs for getting them back in. 
Thanks for the input, but we will be leaving these in for the time being.
