### ISSUE TITLE
env umask not honored

### ISSUE THREAD

**Issue by Celoxocis** [linuxserver/docker-syncthing#26]
there seems to be an issue with the container. by default the ENV umask is set to 022.
when i change it to 007 it keeps it at 022.
so setting the ENV umask in the current state it pretty much broken in it's current state.

**expected behavior:**
file permissions: 007 | 660 (rw-rw----) | directory permissions: 770 (rwxrwx---)
but results in: 022 | 644 (rw-r--r--) | directory permissions: 755 (rwxr-xr-x)

**Comment by sparklyballs** [comment]
the env for this is 

UMASK_SET 

, how are you setting it ?

**Comment by Celoxocis** [comment]
im using a process manager (systemd)

my configuration looks like this:
```
[Unit]
Description=linuxserver/syncthing docker container
After=docker.service
Requires=docker.service

[Service]
User=root
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill syncthing
ExecStartPre=-/usr/bin/docker rm syncthing
ExecStartPre=/usr/bin/docker pull linuxserver/syncthing:latest
ExecStart=/usr/bin/docker run \
        --name syncthing \
        -e PUID=1000 \
        -e PGID=1005 \
        -e TZ=Europe/Berlin \
        -e UMASK_SET=<007> \
        -p 8384:8384 \
        -p 22000:22000 \
        -p 21027:21027/udp \
        -v /home/user/.config/syncthing:/config \
        -v /mnt/personal/files/syncthing:/data1 \
        linuxserver/syncthing:latest
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```
On a side note. I've also noticed that the readme.md under docker usage uses the example:
`-p 21027/udp:21027/udp \`
this doesn't work in systemd and breaks upon start-up with the message:
`docker[7204]: /usr/bin/docker: invalid publish opts format (should be name=value but got '8384:8384').`
hence i had to change it to `-p 21027:21027/udp \` not sure if none-systemd start-up is affected or not.

**Comment by sparklyballs** [comment]
try not using systemd and using as per readme 

if the UMASK_SET works that way , then the issue is systemd.... which isn't something we support using for our containers.

**Comment by sparklyballs** [comment]
also the <007> should be 007 for the value 

the <> denotes a user changeable value............

**Comment by Celoxocis** [comment]
let me redo my config setup. the config paste above actually was what i had left in my notepad++
i'm quite sure i removed the <> in my final systemd setup.
could be wrong though it's was a long day and if it works. it will hopefully work and i can close the issue xD

**Comment by Celoxocis** [comment]
looks like i left the <> in afterall.
it works as expected now! no issues using it with systemd either, except the `21027/udp` part
thanks for the image work! closing issue now! =)
