### ISSUE TITLE
Filesystem Watcher Errors

### ISSUE THREAD

**Issue by ravigupta-art** [linuxserver/docker-syncthing#37]
I am using this docker image to use syncthing.

Installation went fine. But, I keep getting the following error:
`Document OMV  failed to setup inotify handler. Please increase inotify limits, see https://docs.syncthing.net/users/faq.html#inotify-limits`

I used the command on the [page](https://docs.syncthing.net/users/faq.html#inotify-limits) and modified it to be used with docker (docker doesn't recommend using sudo). So, the modified command looked like this: 
`$ echo "fs.inotify.max_user_watches=204800" | tee -a /etc/sysctl.conf`
which output as : 
`fs.inotify.max_user_watches=204800`

Looks like command got executed but the error remains. I restarted Syncthing from GUI and even restarted the container, but the error still remains.

However, the error goes away when the command used in normal Syncthing setup (without docker).

**Comment by thelamer** [comment]
You cannot set sys level inotify limits from within a container . 
A container is not a VM it is a runspace sharing common kernel stuff including these inotify limits set sys level. 

In any case this is not a place for support.

**Comment by ravigupta-art** [comment]
I didn't knew if this was place for support as I thought the error was related to the 'linuxserver/syncthing' image.

As you mentioned, this error is related to docker containers itself . So, I must need to look for support with docker repo ?

**Comment by Mayccoll** [comment]
Maybe a little late,  in the **host** run this command

```bash
echo fs.inotify.max_user_watches=204800 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

**and the container inherits the setting**
