### ISSUE TITLE
Missing /sync directory for UNRAID

### ISSUE THREAD

**Issue by OmgImAlexis** [linuxserver/docker-syncthing#4]
Doesn't ask for a sync directory or even mention that one should be added in the description for UNRAID.
I get that the user can/should add their own mounting path but this would help people just trying it out.

![screen shot 2016-01-10 at 11 32 19 pm](https://cloud.githubusercontent.com/assets/6525926/12221609/705c7d4c-b7f2-11e5-8bdc-ee17bfede4f2.png)

**Comment by lonix** [comment]
You where thinking the template should have a folder called /sync so anyone have a point to start with right ?

The problem then is, if we create a mountpoint in a template, that mountpoint HAS to be furfilled, removing the choise from the user, e.g. I have A two mountpoints 1 for Linuxserver.io stuff  mapped as /linuxserver and one for my dropbox replacement /dropbox

**Comment by OmgImAlexis** [comment]
Yes or at least mention it as an example in the description so people know before starting it that they'll need a directory for files to be synced to.

**Comment by lonix** [comment]
i approve of that comment, and will ensure it happens.

**Comment by CHBMB** [comment]
Was I meant to do something about this over two months ago or something?

**Comment by CHBMB** [comment]
Lonix I've just found this issue whilst perusing github.   I'll add the /sync to the xml.  Although now we're nearly in April it makes a bit of a mockery of your comment " approve of that comment, and **will ensure it happens**." lol
