### ISSUE TITLE
 this command is not available  -v /path/to/appdata/config:/config \

### ISSUE THREAD

**Issue by blckwhtx** [linuxserver/docker-syncthing#40]
I have a lot of docker images from linuxserver and they all work without problems. only the syncthing docker image has problems with the line -v / path / to / appdata / config: / config \. as if the path / config is missing in the docker image

but it works without the path
have checked everything several times

docker run -d \
	--name=syncthing \
	--restart always \
	-p 8384:8384 \
	-p 22000:22000 \
	-p 21027:21027 \
	-v /volume1/docker/syncthing:/config \     # error message --> command unknown line 7
	-d linuxserver/syncthing:amd64-latest

Synology Docker 
CPU  x64

**Comment by aptalca** [comment]
Post the full command you use and the log

**Comment by blckwhtx** [comment]
I close the issue because it doesn't work with the original docker from syncthing either. As soon as I use the "-v" command, an error occurs See 'docker run --help'.
sh: line 7: -d: command not found

but if i start via synology docker assistant then it works and it mounts all paths

strange, because all other docker images run without problems


I have to look further what it is


Thanks anyway

**Comment by aptalca** [comment]
probably has to do with multiple lines and one line not ending with a `\` so it's registered as a newline instead of continuation, thus the `-v` in the next line being treated as if it's a command

That's why I asked you to post the full thing you're trying to run without edits so we can see

**Comment by blckwhtx** [comment]
docker run -d \
	--name=syncthing \
	--restart always \
	-e PUID=1024 \
	-e PGID=100 \
	-p 8384:8384 \
	-p 22000:22000 \
	-p 21027:21027 \
	-v /volume1/docker/syncthing:/config \ 
	-d syncthing/syncthing:nightly

but the \ are set everywhere

**Comment by aptalca** [comment]
`\` should be followed up directly by a newline. What it does is, it tells bash to ignore (escape) the very next character. If you have a space after one of them and then a newline, the space will be escaped and not the newline.

Also, use three backticks before and after to wrap multi line code blocks

**Comment by blckwhtx** [comment]
oh shit, i overlooked that, sorry that i stole your time was a stupid mistake of mine

thank you and have a nice evening
