### ISSUE TITLE
Syncthing does not create the net.core.rmem_max: open /proc/sys/net/core/rmem_max file on startup

### ISSUE THREAD

**Issue by Taubin** [linuxserver/docker-syncthing#50]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Start syncthing through docker-compose which should spin up it's internal (I believe Ubuntu) instance and run. 

## Current Behavior
Syncthing does not create the net.core.rmem_max: open /proc/sys/net/core/rmem_max file on startup which causes it to fail on install. 

## Steps to Reproduce

1. Create docker-compose file with the following: 

```
---
version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /config:/config
      - /data1:/data1
      - /data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    sysctls:
      - net.core.rmem_max=2097152
    restart: unless-stopped
```

2. Attempt to start container with docker-compose up
3. Container will fail to start with the following errors:
```

docker-compose up
Removing syncthing
Recreating c396deb4b344_syncthing ... error

ERROR: for c396deb4b344_syncthing  Cannot start service syncthing: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory: unknown

ERROR: for syncthing  Cannot start service syncthing: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory: unknown
```

4.

## Environment
**OS:** Ubuntu 20.10
**CPU architecture:**  x86_64 
**How docker service was installed:**

It's been ages since I did the install of docker and it's working properly for many other projects, however I believe it was done through the apt install. 

## Command used to create docker container (run/create/compose/screenshot)

```
---
version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /config:/config
      - /data1:/data1
      - /data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    sysctls:
      - net.core.rmem_max=2097152
    restart: unless-stopped
```

## Docker logs
```

docker-compose up
Removing syncthing
Recreating c396deb4b344_syncthing ... error

ERROR: for c396deb4b344_syncthing  Cannot start service syncthing: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory: unknown

ERROR: for syncthing  Cannot start service syncthing: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.core.rmem_max: open /proc/sys/net/core/rmem_max: no such file or directory: unknown
```

This is the only container this has happened with, all of my other containers work fine, including many by Linuxserver.io. It definitely seems to be a bug with this container specifically. I did ask on the discord and got no response from anyone on the issue.

**Comment by stjiub** [comment]
I am having the exact same issue on Ubuntu 20.04.

**Comment by royaltongue** [comment]
Also having this error on Ubuntu 18.04
