### ISSUE TITLE
syncthing volumes - Failed to create folder root directory mkdir /data1: permission denied

### ISSUE THREAD

**Issue by pmoya-in-the-web** [linuxserver/docker-syncthing#55]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Syncthing is not able to use the directories ( /data1 and /data2 ) specified in docker compose. Seems to be a permission problem

If you enter into the web ui and add a folder to share specifying /data1/new_shared_directory

---
version: "2.1"
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/data1:/data1
      - /path/to/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

------------------------------

## Expected Behavior
It should be able to share the new folder

## Current Behavior
It says; 

Failed to create folder root directory mkdir /data1: permission denied

## Environment
**OS:** - Linux raspberrypi 5.10.103-v8+ #1530 SMP PREEMPT Tue Mar 8 13:06:35 GMT 2022 aarch64 GNU/Linux
**CPU architecture:** aarch64
**How docker service was installed:**
From official repo. 

## Command used to create docker container (run/create/compose/screenshot)
docker-compose up -d --remove-orphans

## Docker logs

syncthing    | [NVEE3] 13:23:15 INFO: Detected 1 NAT service
syncthing    | [NVEE3] 13:23:21 INFO: quic://0.0.0.0:22000 detected NAT type: Port restricted NAT
syncthing    | [NVEE3] 13:23:21 INFO: quic://0.0.0.0:22000 resolved external address quic://94.73.44.27:39111 (via stun.syncthing.net:3478)
syncthing    | [NVEE3] 13:23:42 INFO: Joined relay relay://161.97.133.225:22067
syncthing    | [NVEE3] 13:24:35 INFO: Adding folder "xxx_data1" (wk5ke-q4xpg)
syncthing    | [NVEE3] 13:24:35 INFO: No stored folder metadata for "wk5ke-q4xpg"; recalculating
syncthing    | [NVEE3] 13:24:35 WARNING: Failed to create folder root directory mkdir /data1: permission denied
syncthing    | [NVEE3] 13:24:35 INFO: Ready to synchronize "xxx_data1" (wk5ke-q4xpg) (sendreceive)
syncthing    | [NVEE3] 13:24:35 INFO: Failed initial scan of sendreceive folder "xxx_data1" (wk5ke-q4xpg)
syncthing    | [NVEE3] 13:24:35 WARNING: Error on folder "xxx_data1" (wk5ke-q4xpg): folder path missing

**Comment by Milamber07** [comment]
I have the same problem

**Comment by j0nnymoe** [comment]
Closing this issue as the OP has issues due to not changing the default paths within the compose which are there as place holders. 

@Milamber07 open a new issue please providing the information requested.
