### ISSUE TITLE
docs: Mention of data1 and data2 directories is confusing

### ISSUE THREAD

**Issue by gtirloni** [linuxserver/docker-syncthing#57]
The README shows an example of mounting /data1 and /data2 directories inside the container but those paths are nowhere to be found in this Docker image's assets (entrypoint, Dockerfile, etc). I'm guessing those are examples of how to mount something in an area where syncthing will be able to access inside the container but are not actually required.

**Comment by DaniloSteps** [comment]
Hi! I really don't know why the devs didn't addressed this issue. At first I was really confused too and couldn't find an explanation anywhere.
Anyway, after some search I managed to find the answer in [this forum discussion](https://discourse.linuxserver.io/t/data1-data2-locations/3881/4) and it's quite simple. 

> I believe /data1 and /data2 are just examples. For example, let’s say you want to share your entire drive, then you could map /:/host_root_drive so that in the syncthing app, all files are in /host_root_drive/.

**Comment by Milamber07** [comment]
@DaniloSteps @gtirloni 
Hi! Have you found a solution by any chance?

I have the same issue, tried mapping different folders to /data1 and have the same permission mistake... Meanwhile any folder can be created in /config
P.S. using Synology.

**Comment by j0nnymoe** [comment]
@Milamber07 they mention no issue here other than just they don't understand the difference between the 2 mounts. Closing this as there is no more to add.
