### ISSUE TITLE
[FEAT] syncthing deprecated - switch to synching-fork

### ISSUE THREAD

**Issue by Whitehawk2000** [linuxserver/docker-syncthing#82]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Hi, the official syncthing is deprecated. But there is "syncthing-fork" by Catfriend1. It also has already many bugfixes and additional functions. It would be great to swich to this fork. Thank you!

### Reason for change

deprecated official app. bugfixes an new functions

**Comment by Roxedus** [comment]
I dont see why the android app is related to the server software?

**Comment by j0nnymoe** [comment]
Closing as this isn't related to the server software.

**Comment by Whitehawk2000** [comment]
Right after i sent this issue i realized it myself. Tha was before my morning coffee. 🙈
Wanted to delete the issue right away, but cannot find a "delete" button.
